spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fileupload?serverTimezone=Asia/Seoul
    username: root
    password: 159624
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      location: C:\Users\KYC\study\filepractice\filepractice\src\main\resources\img
      maxFileSize: 10MB
      maxRequestSize: 50MB